### ISSUE TITLE
CPS with surround active

### ISSUE THREAD

**Issue by JoSu5S** [ShorelineLLC/issues#11]
**Describe the bug**
The number of crystals per second decreases when I have surround activated, even if I am not trying to place blocks

**To Reproduce**
To reproduce the error activate surround and crystal aura at the same time

**Screenshots**
https://streamable.com/4m7opf

**Environment (please complete the following information):**
 - OS: windows10 official launcher
 - Config: 
[grimcrystalpvpcc.json](https://github.com/user-attachments/files/16720205/grimcrystalpvpcc.json)

**Comment by pastimee** [comment]
Wasnt able to reproduce your issue

https://streamable.com/bg1mqm

**Comment by pastimee** [comment]
Fixed in 55da001
