### ISSUE TITLE
Automine mining issue

### ISSUE THREAD

**Issue by DaggerGotAim** [ShorelineLLC/issues#12]
Auto mine still stops mining pretty frequently and you have to turn it off and on to work
https://www.youtube.com/watch?v=Lh_tWAohk8M

**Comment by DaggerGotAim** [comment]
a simple fix for now would probably being that once it stops mining and recognizes that it turns of automine for a split second and back on.

**Comment by pastimee** [comment]
Fixed in ea1f86a
