### ISSUE TITLE
Improve glow outline in shader

### ISSUE THREAD

**Issue by Flickz1337** [ShorelineLLC/issues#13]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Can we get a better glow outline for the shader? Its okay but other client's glow looks much better imo. I will provide screenshot examples:

![image](https://github.com/user-attachments/assets/afb525bf-b72d-4c70-9895-4d12b7a2bdc2)
this is the shoreline glow

![image](https://github.com/user-attachments/assets/cd9f37ef-26b0-41d2-acc1-ad52df083f8f)
and this is russian client's glow

As you can see their glow looks a little better by having a thin line around the item and then the glow above it whereas our just has this dull glow. I would like to see this be included inside of the Shoreline DLC package. Thank you :D

**Comment by pastimee** [comment]
Added in 0deda07
