### ISSUE TITLE
marble shaders fuck up the whole screen when setting the outline width 3 or above

### ISSUE THREAD

**Issue by Flickz1337** [ShorelineLLC/issues#14]
**Describe the bug**
title

**To Reproduce**
1. turn on shaders
2. select marble mode
3. set outline width to 3 or more

**Expected behavior**
shaders fills the whole screen

**Screenshots**
![image](https://github.com/user-attachments/assets/e8570d56-3674-47d9-821b-148bc36e60b4)

**Environment (please complete the following information):**
 - Config:

**Additional context**

**Comment by pastimee** [comment]
Fixed in 9a9e664
