### ISSUE TITLE
fakeplayer bug when having shaders on

### ISSUE THREAD

**Issue by Flickz1337** [ShorelineLLC/issues#20]
**Describe the bug**
enabling fakeplayer causes to spawn a big version of the fakeplayer too

**To Reproduce**
1. connect to a single or multiplayer server
2. enable shaders
3. enable fakeplayer
4. walk forward and look back at the fakeplayer

**Expected behavior**
spawns in 2 fakeplayers for some reason

**Screenshots**
![image](https://github.com/user-attachments/assets/b1e9f77c-0167-43da-9066-d049c0fd2ae1)

**Environment (please complete the following information):**
 - Config:

**Additional context**

**Comment by pastimee** [comment]
Does this issue happen after restarting game

**Comment by Flickz1337** [comment]
yes

**Comment by pastimee** [comment]
Fixed in 0deda07
