### ISSUE TITLE
Automine anticrawl

### ISSUE THREAD

**Issue by DaggerGotAim** [ShorelineLLC/issues#23]
**Is your feature request related to a problem? Please describe.**
Automine waiting for you to crawl  before performing the anticrawl mine, which could be detrimental if you are being quad mined.
**Describe the solution you'd like**
Instantly once you phase into a 2 block obsidian anticrawl is already mining your head, but only performs if you are only phased into one block and not multiple for maximum production.

**Comment by rarelib** [comment]
yeah i was thinking about this too, sometimes it doesnt anticrawl you and u have to manual it
