### ISSUE TITLE
AutoCrystal rotations mess up strafing on cc

### ISSUE THREAD

**Issue by Flickz1337** [ShorelineLLC/issues#25]
**Describe the bug**
When you have autocrystal enabled strafing is scuffed. This is due to the player rotations

**To Reproduce**
1. go on crystalpvp.cc
2. enable fakeplayer
3. strafe around the fakeplayer
4. enable autocrystal with rotate enabled

**Expected behavior**
strafe to be scuffed when autocrystal is enabled. it is also annoying when fighting against multiple people

**Screenshots**
(https://streamable.com/j86s6k)

**Environment (please complete the following information):**
 - Config:

**Additional context**

**Comment by pastimee** [comment]
Turn off RotationFix in Rotations
