### ISSUE TITLE
loading config causes crash

### ISSUE THREAD

**Issue by Flickz1337** [ShorelineLLC/issues#3]
**Describe the bug**
my game crashes every time i try to change my config

**To Reproduce**
1. connect to a single player world or a server
2. change config in chat (.config load cc)

**Expected behavior**
changing config crashes my game instance

**Screenshots**
![image](https://github.com/user-attachments/assets/aead3923-ef17-4202-9a7c-1c6cbcdc5a38)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Config: my own

**Additional context**
...

**Comment by DaggerGotAim** [comment]
just dmed linus about this today actually lol

**Comment by pastimee** [comment]
Fixed in 99da183
