### ISSUE TITLE
More customizable linewidth in shader.

### ISSUE THREAD

**Issue by lolwut2** [ShorelineLLC/issues#31]
**Is your feature request related to a problem? Please describe.**
Make linewidth in shader more customizable (smaller linewidth), its even when its on 1 very thick.

**Describe the solution you'd like**
make it more customizable.

**Describe alternatives you've considered**

**Additional context**

**Comment by DaggerGotAim** [comment]
Id like to add to this I think old shaders kinda had a better outline, now far away objects become pixelated which is not good. Also if you change the crystal chams the shaders are not pixelated so I think thats weird.

**Comment by pastimee** [comment]
Added in 0deda07
