### ISSUE TITLE
Boze CA (Crystal Aura Update)

### ISSUE THREAD

**Issue by rarelib** [ShorelineLLC/issues#32]
Yes I know it doesnt help with damage or anything like that, but its impossible to play against Boze CA because surround cant keep up, would be nice if shoreline could get this aswell.

**Comment by koushik-lb** [comment]
Are you sure its not just fighting against low ping. I dont think Boze does anything different in CA

**Comment by pastimee** [comment]
Needs more context. I really dont think boze does anything different in CA. Probably just a difference in ping
