### ISSUE TITLE
Silent alt swap sometimes fails on cc

### ISSUE THREAD

**Issue by Flickz1337** [ShorelineLLC/issues#34]
**Describe the bug**
The automine on cc will fail sometimes when in intense combat

**To Reproduce**
1. go on cc
2. load shoreline
3. use automine with silent alt switch
4. look how to the automine gets stuck

**Expected behavior**
automine willk fail to break the block

**Screenshots**
cannot provide a clip as my nvidia experience is fucked

**Environment (please complete the following information):**
 - Config:

**Additional context**

**Comment by pastimee** [comment]
Fixed in 0b56aad
