### ISSUE TITLE
AutoCrystal does not place in 1x1 holes on crystalpvp.cc

### ISSUE THREAD

**Issue by Flickz1337** [ShorelineLLC/issues#35]
**Describe the bug**
When I am fighting the autocrystal does not place in 1x1 holes even when the hole is completely empty

**To Reproduce**
1. connect to crystalpvp.cc
2. fight someone with autocrystal enabled
3. make a hole 1 high
4. autocrystal will not place in that hole

**Expected behavior**
Autocrystal should be able to place in 1x1 holes but it cant for some reason

**Screenshots**
cant clip as nvidia experience is fucked

**Environment (please complete the following information):**
 - Config:

**Additional context**

**Comment by pastimee** [comment]
Wasnt able to recreate. Make sure you have Placements on Native.
https://streamable.com/20u7bc

**Comment by Flickz1337** [comment]
ill try to provide a clip of the issue today

**Comment by Flickz1337** [comment]
nevermind i fixed the issue in my config. didnt have raytrace on. sorry for wasting your time
