### ISSUE TITLE
Can we have a smooth progress color for the automine?

### ISSUE THREAD

**Issue by Flickz1337** [ShorelineLLC/issues#36]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Similar to blackout automine, their color will smoothly change from one color to a different color based on the progress of the automine. I would like to see this be implemented into shoreline's automine rendering as it would look much better in my opinion.

**Describe alternatives you've considered**

**Additional context**
Just look at blackout's colors in their automine and you will understand what i mean.

**Comment by pastimee** [comment]
Added in dbd81d2
