### ISSUE TITLE
player chams fill issue and hand chams issue

### ISSUE THREAD

**Issue by Flickz1337** [ShorelineLLC/issues#37]
**Describe the bug**
Look at the clip and the screenshot i have provided. The chams texture bugs out on the player and the hand chams are not in the right place at all

**To Reproduce**

**Expected behavior**

**Screenshots**
https://streamable.com/2thxog
player chams issue

![image](https://github.com/user-attachments/assets/68ebb1db-9c70-4706-8b5d-f6b4c557ef47)
hand chams issue

**Environment (please complete the following information):**
 - Config:

**Additional context**

**Comment by Flickz1337** [comment]
btw disabling through walls causes the issue with player chams

**Comment by pastimee** [comment]
1st issue resolved in 6a441ec.
2nd issue fixed in d674b9e.
