### ISSUE TITLE
Holefill rubberbanding on cc

### ISSUE THREAD

**Issue by Flickz1337** [ShorelineLLC/issues#38]
**Describe the bug**
holefill rubberbanding me on cc

**To Reproduce**
1. connect to cc
2. turn on holefill with auto enabled
3. fight and rubberband

**Screenshots**
https://streamable.com/b3rvzv
https://streamable.com/yk7wyz

**Environment (please complete the following information):**
 - Config:

**Additional context**
pls fix

**Comment by Flickz1337** [comment]
probably mentioned this before but the rubberband occurs with any module that needs to place blocks

**Comment by pastimee** [comment]
Fixed in ac1883a
