### ISSUE TITLE
omnidirectional sprint for 2b

### ISSUE THREAD

**Issue by Flickz1337** [ShorelineLLC/issues#39]
**Is your feature request related to a problem? Please describe.**
yes i am angry that i cant sprint in all directions on 2b2t my life has become depressing because of this

**Describe the solution you'd like**
Omnidirectional sprint allows you to sprint in all directions. it gives you the power to have all movement capabilities.

**Describe alternatives you've considered**

**Additional context**

**Comment by pastimee** [comment]
Added in 7c62e68
