### ISSUE TITLE
trails for projectile items (pearls, arrows etc)

### ISSUE THREAD

**Issue by Flickz1337** [ShorelineLLC/issues#40]
**Is your feature request related to a problem? Please describe.**
nope

**Describe the solution you'd like**
would like to see trails included as it would make it easier to see when someone throws a pearl

**Describe alternatives you've considered**
just trails

**Additional context**
![image](https://github.com/user-attachments/assets/6bf5217e-7de6-4990-b053-1b789cec7524)

**Comment by pastimee** [comment]
I feel like this is unnecessary since we have pearl nametags

**Comment by Flickz1337** [comment]
yeah its not like we need it but its a nice little thing to have added. most people in the discord can agree

**Comment by pastimee** [comment]
Added in adbd408
