### ISSUE TITLE
Automine silent swap bugging (may cause eat failure/mine failure)

### ISSUE THREAD

**Issue by DaggerGotAim** [ShorelineLLC/issues#5]
**Describe the bug**

**To Reproduce**
Go to grim cc use an account to watch the other account manual mine and you can see even with silent swap on you periodically switch to your pickaxe for some reason

**Expected behavior**
no switching at all

**Screenshots**
not needed its self-explanatory 

**Environment (please complete the following information):**
 -

**Additional context**

**Comment by hockeyl8** [comment]
Can you show what you mean by this?

**Comment by pastimee** [comment]
Fixed in 3743e1d
