### ISSUE TITLE
biggie apple

### ISSUE THREAD

**Issue by rarelib** [ShorelineLLC/issues#58]
![Minecraft Screenshot 2024 09 09 - 23 15 05 39](https://github.com/user-attachments/assets/9ef9fdf7-38e8-47e1-ace3-f47db9c9b118)

Shows big apple above player when they are holding a gapple

**Comment by pastimee** [comment]
How to recreate, Im not able to recreate? Context for issue?

**Comment by hockeyl8** [comment]
Iris shader issue
