### ISSUE TITLE
Shadow option for hud text

### ISSUE THREAD

**Issue by Flickz1337** [ShorelineLLC/issues#63]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Clients in 1.12 had a shadow option for the hud where it would minimize the shadow length on text

**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/user-attachments/assets/518c72fd-bf05-41fd-837c-c905bd0ba900)
with shadow on

![image](https://github.com/user-attachments/assets/8a313f6d-f1ef-4d92-9e30-92bf15e45567)
without shadow on

**Comment by pastimee** [comment]
Added in e1e3394
