### ISSUE TITLE
Smart Anticrawl Option

### ISSUE THREAD

**Issue by rarelib** [ShorelineLLC/issues#66]
Make anticrawl mine down instead of up on certain scenarios.

If fighting an enemy or within range, if below that block is air, and if the block below is minable.
Note: The anticrawl should only keep you 1 block below the enemy within range.
Would be strong because the lower you are the better.

Should be a sub option.

Automine
>Anticrawl
   "Smart"

**Comment by pastimee** [comment]
Added in 3cf0ca3
